version: "3"
services:

  db:
    container_name: ca_url_shortener_db
    image: postgres:14
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ca_url_shortener_data:/var/lib/postgresql/data

volumes:
  ca_url_shortener_data:
